In [3]:
import numpy as np
print(np.__version__)

1.13.3


## Useful keyboard shortcuts

_For PC_

- SHIFT-ENTER: runs the cell
- CTRL-ENTER: runs the cell, move to the next cell
- ALT-ENTER: runs the cell, inserts a new cell after
- CTRL-M + M: changes the cell type to _Markdown_.

In [4]:
grades = [89, 90, 67, 78, 85]

In [8]:
grades_array = np.array(grades, dtype=float)

In [9]:
grades_array.dtype

dtype('float64')

In [10]:
grades_array

array([ 89.,  90.,  67.,  78.,  85.])

In [13]:
grades_array[3], grades_array[-1]

(78.0, 85.0)

# 2D numpy array

In [14]:
matrix_py = [[1,2,3,4,5],
            [10,20,30,40,50],
            [-1,-2,-3,-4,-5]]

In [15]:
matrix_np = np.array(matrix_py, dtype=float)

In [16]:
matrix_np

array([[  1.,   2.,   3.,   4.,   5.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ -1.,  -2.,  -3.,  -4.,  -5.]])

In [17]:
matrix_np.shape

(3, 5)

# Higher dimensional ndarrays

We can build higher dimensional arrays.

In [24]:
ndarray_3d = np.array([matrix_np, matrix_np+10, matrix_np+100])

In [25]:
ndarray_3d

array([[[   1.,    2.,    3.,    4.,    5.],
        [  10.,   20.,   30.,   40.,   50.],
        [  -1.,   -2.,   -3.,   -4.,   -5.]],

       [[  11.,   12.,   13.,   14.,   15.],
        [  20.,   30.,   40.,   50.,   60.],
        [   9.,    8.,    7.,    6.,    5.]],

       [[ 101.,  102.,  103.,  104.,  105.],
        [ 110.,  120.,  130.,  140.,  150.],
        [  99.,   98.,   97.,   96.,   95.]]])

In [26]:
ndarray_3d.shape

(3, 3, 5)

In [27]:
grades_array.shape

(5,)

# Zero-dimensional ndarray

In [28]:
scalar = np.array(3.1415)

In [29]:
scalar

array(3.1415)

In [30]:
scalar.shape

()

# Basic index

In [4]:
X = np.array([[1, 2],
              [3, 4],
              [5, 6],
              [7, 8]])

In [5]:
X.shape

(4, 2)

In [7]:
X[2, 1]

6

# Slicing along dimensions

In [8]:
X[0,1]

2

In [9]:
X[0:2, 1]

array([2, 4])

In [10]:
X[:2, :]

array([[1, 2],
       [3, 4]])

In [11]:
X[::2, :]

array([[1, 2],
       [5, 6]])

In [19]:
X[:3, :]

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
X.shape

(4, 2)

In [21]:
X[:2, :1].shape

(2, 1)

In [24]:
X[:3, 0].shape

(3,)

In [23]:
X[3, :].shape

(2,)

# Transpose

In [25]:
X

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [26]:
np.transpose(X)

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

# Reshape

In [27]:
X = np.array([[1,2,3,4],
             [2,3,4,5],
             [5,6,7,8]])

In [28]:
np.product(X.shape)

12

In [29]:
(3,4), (4,3), (2,6), (6,2), (2,2,3), (3,2,2), (12, 1)

((3, 4), (4, 3), (2, 6), (6, 2), (2, 2, 3), (3, 2, 2), (12, 1))

In [30]:
np.reshape(X, (4,3))

array([[1, 2, 3],
       [4, 2, 3],
       [4, 5, 5],
       [6, 7, 8]])

In [31]:
shape = (3,4,10,20)

In [33]:
np.product(shape)

2400

In [39]:
vector = np.array(list(range(np.product(shape))))

In [40]:
array = np.reshape(vector, shape)

In [42]:
array.shape

(3, 4, 10, 20)